Repository ponylang/glob, pull requests merged in 2022-02, with the labels that each got.

#29 Add nodoc annotation to test code
  glob/_test.pony
Labels: discuss during sync

#30 Update to work with object capabilities changes in Pony 0.49.0
  .release-notes/obj-cap.md
  glob/_test.pony
Labels: changelog - changed, discuss during sync

#31 Update to work with PonyTest change introduced in 0.49.0
  .release-notes/31.md
  corral.json
  glob/_test.pony
  lock.json
Labels: changelog - fixed, discuss during sync
